name: opengov_app
description: Participant/admin UI for OpenGov.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  datetime_picker_formfield: ^2.0.0
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  opengov_common:
    path: ../common
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#A51C30"
  adaptive_icon_foreground: "assets/images/gavel.png"
