name: opengov_server
description: Back-end server for OpenGov.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  opengov_common:
    path: ../common
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  sqflite_common: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.1
  shelf_router_generator: ^1.0.1
  sqflite_common_ffi: ^2.1.0
