name: opengov_common
description: Common classes for the OpenGov project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  crypto: ^3.0.1
  duration: ^3.0.8
  intl: ^0.17.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  lints: ^1.0.1
